export const CartesSignaturesAromatiquesMobileTablette = [
    {
        id: "herbaces",
        titre: "Herbacés",
        largeurBarreSeparation: "w-[100px] xs:w-[105px] xsm:w-[125px] sm:w-[150px] md:w-[155px]",
        texte: "Basilic, thym, romarin, coriandre et menthe apportent fraîcheur et profondeur à nos plats.",
        image: "/images/herbaces.png",
        alt: "Image avec plusieurs herbacés : ciboulette, romarin, basilic et thin.",
        width: 282,
        height: 317,
        animation: "animation-apparition-fondu-gauche",
        delay: 1200,
        animationOuverture: "animation-ouverture-carte",
        animationFermeture: "animation-fermeture-carte",
        imagesGroupe: [
            {
                src: "/images/herbaces/menthe/menthe_2.png",
                alt: "Deux feuilles de menthe superposées.",
                width: 435,
                height: 232,
                className: "absolute top-[1%] xs:top-[1%] xsm:top-[1%] md:top-[1%] right-[73%] xs:right-[75%] xsm:right-[75%] sm:right-[77%] md:right-[78%] w-[32%] xsm:w-[30%] sm:w-[28%] md:w-[26%] h-auto rotate-320 animation-zoom-leger",
            },
            {
                src: "/images/herbaces/basilic/basilic_2.png",
                alt: "Groupe de quatre à cinq feuilles de basilic.",
                width: 186,
                height: 394,
                className: "absolute top-[20%] sm:top-[22%] md:top-[26%] left-[83%] sm:left-[86%] md:left-[88%] w-[18%] xsm:w-[16%] sm:w-[14%] md:w-[12%] h-auto rotate-230 animation-zoom-leger",
            },
            {
                src: "/images/herbaces/thym/thym_1.png",
                alt: "Brin de thym avec plusieurs rameaux.",
                width: 306,
                height: 322,
                className: "absolute top-[70%] sm:top-[68%] md:top-[66%] right-[79%] md:right-[84%] w-[26%] xsm:w-[24%] sm:w-[22%] md:w-[20%] h-auto rotate-260 animation-zoom-leger",
            },
        ],
    },
    {
        id: "agrumes",
        titre: "Agrumes",
        largeurBarreSeparation: "w-[90px] xs:w-[100px] xsm:w-[120px] sm:w-[145px] md:w-[150px]",
        texte: "Citron, orange et pamplemousse apportent fraîcheur et vivacité à chaque assiette.",
        image: "/images/agrumes.png",
        alt: "Image avec plusieurs agrumes découpés en tranches : pamplemousse, orange et citron vert.",
        width: 600,
        height: 600,
        animation: "animation-apparition-fondu-droite",
        delay: 1400,
        animationOuverture: "animation-ouverture-carte",
        animationFermeture: "animation-fermeture-carte",
        imagesGroupe: [
            {
                src: "/images/agrumes/pamplemouses/pamplemousse_1.png",
                alt: "Une demi tranche de pamplemousse.",
                width: 435,
                height: 232,
                className: "absolute -top-[2%] xs:-top-[3%] xsm:-top-[3%] sm:-top-[3%] md:-top-[3%] right-[74%] xs:right-[78%] xsm:right-[80%] md:right-[82%] w-[26%] xs:w-[24%] xsm:w-[22%] sm:w-[20%] md:w-[18%] h-auto rotate-190 animation-zoom-leger",
            },
            {
                src: "/images/agrumes/citrons_vert/citron_vert_2.png",
                alt: "Un trois-quarts de tranche de citron vert.",
                width: 263,
                height: 301,
                className: "absolute top-[24%] sm:top-[18%] md:top-[20%] left-[75%] xs:left-[78%] xsm:left-[80%] w-[28%] xs:w-[26%] xsm:w-[24%] sm:w-[26%] md:w-[24%] h-auto rotate-350 animation-zoom-leger",
            },
            {
                src: "/images/agrumes/oranges/orange_2.png",
                alt: "Un quartier d'orange.",
                width: 261,
                height: 244,
                className: "absolute top-[73%] xs:top-[72%] sm:top-[70%] md:top-[68%] right-[75%] xs:right-[78%] sm:right-[84%] w-[28%] xs:w-[26%] xsm:w-[24%] sm:w-[22%] md:w-[20%] h-auto -rotate-5 animation-zoom-leger",
            },
        ],
    },
    {
        id: "florals",
        titre: "Florals",
        largeurBarreSeparation: "w-[70px] xs:w-[85px] xsm:w-[90px] sm:w-[110px] md:w-[115px]",
        texte: "Jasmin, rose, lavande et fleur d’oranger dévoilent douceur et délicatesse au fil des saveurs.",
        image: "/images/florals.png",
        alt: "Image avec un mélange de plusieurs fleurs comestibles : rose, lavande, fleur d’oranger et badiane.",
        width: 282,
        height: 317,
        animation: "animation-apparition-fondu-gauche",
        delay: 1600,
        animationOuverture: "animation-ouverture-carte",
        animationFermeture: "animation-fermeture-carte",
        imagesGroupe: [
            {
                src: "/images/florals/rose_rouge/rose_rouge_1.png",
                alt: "Une pétale de rose rouge.",
                width: 435,
                height: 232,
                className: "absolute top-[4%] xs:top-[4%] xsm:top-[4%] md:top-[4%] right-[90%] xs:right-[90%] xsm:right-[90%] md:right-[90%] w-[14%] sm:w-[12%] h-auto rotate-40 animation-zoom-leger",
            },
            {
                src: "/images/florals/rose_rouge/rose_rouge_2.png",
                alt: "Une pétale de rose rouge.",
                width: 435,
                height: 232,
                className: "absolute -top-[1%] xs:-top[1%] xsm:-top-[1%] md:-top-[1%] right-[80%] xs:right-[80%] xsm:right-[80%] sm:right-[82%] md:right-[82%] w-[14%] sm:w-[12%] h-auto rotate-310 animation-zoom-leger",
            },

            {
                src: "/images/florals/frangipanier/frangipanier_3.png",
                alt: "Une fleur de frangipanier.",
                width: 186,
                height: 394,
                className: "absolute top-[24%] sm:top-[24%] md:top-[24%] left-[78%] w-[26%] h-auto rotate-230 animation-zoom-leger",
            },

            {
                src: "/images/florals/rose_jaune/rose_jaune_1.png",
                alt: "Une pétale de rose jaune.",
                width: 306,
                height: 322,
                className: "absolute top-[84%] sm:top-[80%] md:top-[80%] right-[86%] sm:right-[88%] w-[16%] sm:w-[14%] h-auto rotate-40 animation-zoom-leger",
            },
        ],
    },
    {
        id: "epices",
        titre: "Épicés",
        largeurBarreSeparation: "w-[70px] xs:w-[85px] xsm:w-[90px] sm:w-[110px] md:w-[115px]",
        texte: "Des épices sélectionnées pour apporter caractère et intensité à nos créations.",
        image: "/images/epices.png",
        alt: "Image avec plusieurs épices : poivre rouge, noir et blanc, piments rouges et jaunes.",
        width: 282,
        height: 317,
        animation: "animation-apparition-fondu-droite",
        delay: 1800,
        animationOuverture: "animation-ouverture-carte",
        animationFermeture: "animation-fermeture-carte",
        imagesGroupe: [
            {
                src: "/images/epices/poivre_rouge/poivre_rouge_1.png",
                alt: "Un grain de poivre rouge.",
                width: 435,
                height: 232,
                className: "absolute top-[4%] xs:top-[4%] xsm:top-[4%] md:top-[6%] right-[90%] xs:right-[90%] xsm:right-[90%] sm:right-[94%] md:right-[92%] w-[14%] sm:w-[10%] md:w-[10%] h-auto rotate-40 animation-zoom-leger",
            },
            {
                src: "/images/epices/poivre_rouge/poivre_rouge_4.png",
                alt: "Un grain de poivre rouge.",
                width: 435,
                height: 232,
                className: "absolute -top-[3%] xs:-top[1%] xsm:-top-[1%] sm:-top-[2%] md:-top-[1%] right-[82%] xs:right-[80%] xsm:right-[80%] sm:right-[86%] md:right-[88%] w-[10%] sm:w-[8%] md:w-[6%] h-auto rotate-310 animation-zoom-leger",
            },

            {
                src: "/images/epices/piment/piment_rouge_1.png",
                alt: "Morceau de piment rouge avec des graines blanches à l'intérieur.",
                width: 186,
                height: 394,
                className: "absolute top-[24%] sm:top-[28%] md:top-[26%] left-[82%] xs:left-[88%] xsm:left-[88%] sm:left-[90%] md:left-[90%] w-[20%] xs:w-[18%] xsm:w-[16%] sm:w-[14%] h-auto rotate-200 animation-zoom-leger",
            },
            

            {
                src: "/images/epices/poivre_noir/poivre_noir_1.png",
                alt: "Un grain de poivre noir.",
                width: 306,
                height: 322,
                className: "absolute top-[76%] sm:top-[73%] md:top-[75%] right-[96%] sm:right-[94%] md:right-[96%] w-[8%] sm:w-[8%] md:w-[6%] h-auto rotate-40 animation-zoom-leger",
            },
            {
                src: "/images/epices/poivre_noir/poivre_noir_1.png",
                alt: "Un grain de poivre noir.",
                width: 306,
                height: 322,
                className: "absolute top-[84%] sm:top-[84%] md:top-[84%] right-[86%] sm:right-[88%] md:right-[90%] w-[12%] sm:w-[10%] md:w-[8%] h-auto rotate-40 animation-zoom-leger",
            }, 
            {
                src: "/images/epices/poivre_noir/poivre_noir_1.png",
                alt: "Un grain de poivre noir.",
                width: 306,
                height: 322,
                className: "absolute top-[86%] sm:top-[84%] md:top-[86%] right-[77%] sm:right-[79%] md:right-[84%] w-[6%] sm:w-[6%] md:w-[4%] h-auto rotate-40 animation-zoom-leger",
            },
        ],
    },
];

export const CartesSignaturesAromatiquesPC = [
    {
        id: "herbaces",
        titre: "Herbacés",
        largeurBarreSeparation: "w-[125px]",
        texte: "Basilic, thym, romarin, coriandre et menthe apportent fraîcheur et profondeur à nos plats.",
        image: "/images/herbaces.png",
        alt: "Image avec plusieurs herbacés : ciboulette, romarin, basilic et thin.",
        width: 282,
        height: 317,
        animation: "animation-apparition-fondu-gauche",
        delay: 1200,
        animationOuverture: "animation-ouverture-carte-gauche",
        animationFermeture: "animation-fermeture-carte-gauche",
    },
    {
        id: "agrumes",
        titre: "Agrumes",
        largeurBarreSeparation: "w-[115px]",
        texte: "Citron, orange et pamplemousse apportent fraîcheur et vivacité à chaque assiette.",
        image: "/images/agrumes.png",
        alt: "Image avec plusieurs agrumes découpés en tranches : pamplemousse, orange et citron vert.",
        width: 600,
        height: 600,
        animation: "animation-apparition-fondu-droite",
        delay: 1400,
        animationOuverture: "animation-ouverture-carte-gauche",
        animationFermeture: "animation-fermeture-carte-gauche",
    },
    {
        id: "florals",
        titre: "Florals",
        largeurBarreSeparation: "w-[90px]",
        texte: "Jasmin, rose, lavande et fleur d’oranger dévoilent douceur et délicatesse au fil des saveurs.",
        image: "/images/florals.png",
        alt: "Image avec un mélange de plusieurs fleurs comestibles : rose, lavande, fleur d’oranger et badiane.",
        width: 282,
        height: 317,
        animation: "animation-apparition-fondu-gauche",
        delay: 1600,
        animationOuverture: "animation-ouverture-carte-gauche",
        animationFermeture: "animation-fermeture-carte-gauche",
    },
    {
        id: "epices",
        titre: "Épicés",
        largeurBarreSeparation: "w-[90px]",
        texte: "Des épices sélectionnées pour apporter caractère et intensité à nos créations.",
        image: "/images/epices.png",
        alt: "Image avec plusieurs épices : poivre rouge, noir et blanc, piments rouges et jaunes.",
        width: 282,
        height: 317,
        animation: "animation-apparition-fondu-droite",
        delay: 1800,
        animationOuverture: "animation-ouverture-carte-gauche",
        animationFermeture: "animation-fermeture-carte-gauche",
    },
];

